export const PLAYLIST_CODES = {
  NOT_FOUND: 'PLAYLIST_NOT_FOUND',
  INVALID_INPUT: 'INVALID_PLAYLIST_INPUT',
  CREATION_FAILED: 'PLAYLIST_CREATION_FAILED',
  DELETION_FAILED: 'PLAYLIST_DELETION_FAILED',
  ALREADY_EXISTS: 'CONFLICT_PLAYLIST',
  ADD_SONG_FAILED: 'ADD_SONG_TO_PLAYLIST_FAILED',
  REMOVE_SONG_FAILED: 'REMOVE_SONG_FROM_PLAYLIST_FAILED',
  UPDATE_FAILED: 'PLAYLIST_UPDATE_FAILED',
  GET_SONGS_FAILED: 'GET_PLAYLIST_SONGS_FAILED',
  GET_SHARED_FAILED: 'GET_SHARED_PLAYLISTS_FAILED',
};
export const PLAYLIST_MESSAGES = {
  NOT_FOUND: 'Playlist not found.',
  INVALID_INPUT: 'Invalid input for playlist.',
  CREATION_FAILED: 'Failed to create the playlist.',
  DELETION_FAILED: 'Failed to delete the playlist.',
  ALREADY_EXISTS: 'Playlist with title already exists for user',
  ADD_SONG_FAILED: 'Failed to add song to playlist.',
  REMOVE_SONG_FAILED: 'Failed to remove song from playlist.',
  UPDATE_FAILED: 'Failed to update playlist.',
  UPDATE_SUCCESS: 'Playlist updated successfully.',
  GET_SONGS_FAILED: 'Failed to retrieve songs from playlist.',
  GET_SHARED_FAILED: 'Failed to retrieve shared playlists.',
};
